---
services:
  mqtt-bridge:
    image: svenschmidt1502/mqtt-bridge:latest
    container_name: mqtt-bridge
    environment:
      - 'MQTT_BROKER=${MQTT_BROKER}'
      - 'MQTT_PORT=${MQTT_PORT}'
      - 'KAFKA_BROKER=${KAFKA_BROKER}'
      - 'KAFKA_TOPIC=${KAFKA_TOPIC}'
      - 'MQTT_USERNAME=${MQTT_USERNAME}' 
      - 'MQTT_PASSWORD=${MQTT_PASSWORD}' 
      - 'MQTT_TOPICS=${MQTT_TOPICS}'
      - 'KAFKA_TOPIC_MAPPING=${KAFKA_TOPIC_MAPPING}'
    network_mode: host


